%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.username=quarkus_test
%prod.quarkus.datasource.password=quarkus_test
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:15432/quarkus_test
%prod.quarkus.datasource.jdbc.max-size=8
%prod.quarkus.datasource.jdbc.min-size=2

#%test.quarkus.datasource.db-kind=h2
#%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
%test.quarkus.datasource.devservices.enabled=false



quarkus.openapi.generator.spec=warehouse-openapi.yaml
quarkus.openapi.generator.base-package=com.warehouse.api

# Pass JaCoCo agent into the Quarkus child JVM for coverage
quarkus.test.arg-line=${argLine}
quarkus.jacoco.report=true
quarkus.jacoco.report-location=target/jacoco-report

# Important: Reuse the same data file across Surefire and Failsafe
quarkus.jacoco.reuse-data-file=true


# ================== TEST (Critical for ITs) ==================
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
%test.quarkus.datasource.jdbc.driver=org.h2.Driver

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql
quarkus.hibernate-orm.log.sql=true

# Force test profile for integration tests
quarkus.test.integration-test-profile=test